"""add content_md

Revision ID: ead581e7144d
Revises: 521ea364623c
Create Date: 2021-02-05 10:08:23.433992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead581e7144d'
down_revision = '521ea364623c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content_md')
    # ### end Alembic commands ###
